### ISSUE TITLE
Panic when proceeding anonymous struct pointer

### ISSUE THREAD

**Issue by Andrew-M-C** [Andrew-M-C/go.jsonvalue#22]
[playground](https://go.dev/play/p/GdcE_407ysz)

```go
package main

import (
	"fmt"

	jsonvalue "github.com/Andrew-M-C/go.jsonvalue"
)

func main() {
	type inner struct {
		Name string
	}
	type outer struct {
		*inner
		Age int
	}

	person := &outer{}
	person.inner = &inner{}
	person.Name = "Andrew"

	s := jsonvalue.New(person).MustMarshalString()

	fmt.Println(s)
}

```

Got: 
```
panic: reflect: call of reflect.Value.NumField on ptr Value

goroutine 1 [running]:
reflect.flag.mustBe(...)
	/usr/local/go-faketime/src/reflect/value.go:221
reflect.Value.NumField({0x4c8b80?, 0xc000014300?, 0x7fb6d6408600?})
	/usr/local/go-faketime/src/reflect/value.go:1963 +0x8d
github.com/Andrew-M-C/go%2ejsonvalue.parseStructFieldValue({0x4c8b80?, 0xc000014300?, 0x7fb6d6403700?}, {{0x4c2865, 0x5}, {0x4c22eb, 0x4}, {0x50bc60, 0x4c8b80}, {0x0, ...}, ...}, ...)
	/tmp/gopath2056463688/pkg/mod/github.com/!andrew-!m-!c/go.jsonvalue@v1.3.2/import_export.go:345 +0x3da
github.com/Andrew-M-C/go%2ejsonvalue.parseStructValue({0x4d4560?, 0xc000014300?, 0x0?}, {0xe0?, 0x61?, 0x5d?})
	/tmp/gopath2056463688/pkg/mod/github.com/!andrew-!m-!c/go.jsonvalue@v1.3.2/import_export.go:321 +0x1d5
github.com/Andrew-M-C/go%2ejsonvalue.parsePtrValue({0x4c8bc0?, 0xc000014300?, 0x0?}, {0x8?, 0x32?, 0xa8?})
	/tmp/gopath2056463688/pkg/mod/github.com/!andrew-!m-!c/go.jsonvalue@v1.3.2/import_export.go:270 +0x12a
github.com/Andrew-M-C/go%2ejsonvalue.Import({0x4c8bc0, 0xc000014300}, {0x0?, 0x0?, 0x0?})
	/tmp/gopath2056463688/pkg/mod/github.com/!andrew-!m-!c/go.jsonvalue@v1.3.2/import_export.go:34 +0xfd
github.com/Andrew-M-C/go%2ejsonvalue.New(...)
	/tmp/gopath2056463688/pkg/mod/github.com/!andrew-!m-!c/go.jsonvalue@v1.3.2/new.go:19
main.main()
	/tmp/sandbox2041220080/prog.go:24 +0x99
```

**Comment by Andrew-M-C** [comment]
fixed and released
